## 0. Importing NumPy
To get started using NumPy, the first step is to import it.

The most common way (and method you should use) is to import NumPy as the abbreviation np.

If you see the letters np used anywhere in machine learning or data science, it's probably referring to the NumPy library.

In [2]:
import numpy as np

#check the version
print(np.__version__)

1.26.4



1. DataTypes and attributes

    Note: Important to remember the main type in NumPy is ndarray, even seemingly different kinds of arrays are still ndarray's. This means an operation you do on one array, will work on another.



In [3]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

# 3-dimensional array, also referred to as a matrix
a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])


In [4]:
a1.shape

(3,)

In [5]:
a1.ndim, a1.size, a1.dtype, type(a1)

(1, 3, dtype('int64'), numpy.ndarray)

In [6]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [7]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [8]:
a1

array([1, 2, 3])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# Anatomy of an array

![](anatomy_ndarrays.png)

Key terms:

    Array - A list of numbers, can be multi-dimensional.
    Scalar - A single number (e.g. 7).
    Vector - A list of numbers with 1-dimension (e.g. np.array([1, 2, 3])).
    Matrix - A (usually) multi-dimensional list of numbers (e.g. np.array([[1, 2, 3], [4, 5, 6]])).



pandas DataFrame out of NumPy arrays

This is to examplify how NumPy is the backbone of many other libraries.


In [15]:
import pandas as pd

# np.random.randint(10, size=(5, 3)):
# This generates a 2D array (matrix) of random integers.
# 10: Specifies the upper limit for the random integers (0 to 9).
# size=(5, 3): Specifies the shape of the array—5 rows and 3 columns.
df= pd.DataFrame(np.random.randint(10, size=(5,3)),columns=['a','b','c'])

df

a  b  c
0  5  1  0
1  2  5  0
2  5  3  1
3  5  1  4
4  0  1  3

In [16]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [18]:
df2= pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5