In [1]:
import numpy as np

#check version
np.__version__


'1.26.4'

In [2]:
# a vector: the argument to the array function is a Python list
# more generally, 1D array
lst = [1, 2, 3,4,0]
v = np.array(lst, dtype=np.int32)
v

array([1, 2, 3, 4, 0], dtype=int32)

In [3]:
np.array([1,2,3,4], dtype=np.int32)

array([1, 2, 3, 4], dtype=int32)

In [4]:

# a matrix: the argument to the array function is a nested Python list (can also be a tuple of tuples)
# more generally, a 2D array
list_of_lists = [[1,2],[3,4]]
M = np.array(list_of_lists)
M

array([[1, 2],
       [3, 4]])

In [5]:
# a row vector

row_vec = v[np.newaxis,:] # v[None,:]
row_vec

array([[1, 2, 3, 4, 0]], dtype=int32)

In [6]:
np.array([[1,2,3,4]], dtype=np.int32)

array([[1, 2, 3, 4]], dtype=int32)

In [7]:
# a column vector
col_vec = v[:, np.newaxis] #v[:, None]
col_vec

array([[1],
       [2],
       [3],
       [4],
       [0]], dtype=int32)

In [8]:
np.array([[1],[2],[3],[4]], dtype=np.int32)

array([[1],
       [2],
       [3],
       [4]], dtype=int32)

In [9]:
# when using linspace, both end points are included
'''return evenly spaced numbers over a specified interval.

    Returns num evenly spaced samples, calculated over the interval [start, stop].

    The endpoint of the interval can optionally be excluded.'''
np.linspace(0, 10)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [10]:
''' np.logspace(start, stop, num=50, endpoint=True, base=10.0(algorithm), dtype=None, axis=0)'''
np.logspace(0, 5, 10, base=np.e)


array([  1.        ,   1.742909  ,   3.03773178,   5.29449005,
         9.22781435,  16.08324067,  28.03162489,  48.85657127,
        85.15255772, 148.4131591 ])

In [11]:
# a 3D array
# a random array where the values come from a standard normal distribution
'''random.randn(d0, d1, ..., dn)'''
gaussian = np.random.randn(2*3*4)

#resahpe the array to desitred shape
# only the number of dimensions can be altered
#the number of elements cannot be changed during a reshape operation

gaussian = gaussian.reshape((2,3,4))
gaussian

array([[[-0.68186114,  0.0801222 ,  0.22665175,  1.08825406],
        [ 0.44633362,  0.56920223,  0.10666529,  0.63898688],
        [ 2.97224329,  2.20702588,  0.25860765,  0.27420719]],

       [[ 0.72545361,  0.14066037,  0.81850556, -0.7754722 ],
        [ 1.05215243,  0.89010158,  0.22505352,  0.4213133 ],
        [ 0.0592586 ,  1.07037489,  0.10998035, -1.88998259]]])

In [12]:
# an array full of zero values
# one can also specify a desired datatype

'''np.zeros(shape, dtype=float, order='C')'''
zero_arr = np.zeros((3,4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# an array full of ones
# one can also specify datatype

ones_arr = np.ones((3,4), dtype=np.float32)
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [14]:
# a 3*3 identity (matrix) array
# An identity matrix is a square matrix where all the diagonal elements are 1, and all other elements are 0.
'''np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')'''
iden = np.identity(3, dtype= np.float128)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float128)

In [15]:
# a diagonal array

diag = np.diag([1,2,3,4.0])
diag

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

In [16]:
# a 3D random array where the values come from a standard Normal distribution
#2*3*4 is evaluated as 24, meaning np.random.randn(24) generates 24 random values.
gaussian = np.random.randn(2*3*4).reshape((2,3,4))
print(gaussian)

[[[ 0.37370734  0.77707572  0.39479029  2.06444282]
  [ 0.21155995 -1.92305457 -0.53447782  0.48880559]
  [-1.14977691 -0.23090384  0.98816237 -0.6766298 ]]

 [[-0.34154272  1.2993996  -0.2224029   0.10834705]
  [-0.6096913   0.01739315 -0.66088687 -0.5212048 ]
  [ 1.69474931  1.64248018 -0.17405049 -1.46282699]]]


In [17]:
# get number fo dimensions fo the array
gaussian.ndim
print("total dimensions of the array is : ", gaussian.ndim)

#get the shape of the array
gaussian.shape
print("shape of the array is : ", gaussian.shape)

#get the total number of elements in array
gaussian.size
print("total number of items is: ", gaussian.size)

# get memory consumed by each item in the array
gaussian.itemsize
print("memory consumed by each item is : ", gaussian.itemsize)

#get memory consumed by the array
gaussian.nbytes
print("memory consumed by the whole array is : ", gaussian.nbytes)

total dimensions of the array is :  3
shape of the array is :  (2, 3, 4)
total number of items is:  24
memory consumed by each item is :  8
memory consumed by the whole array is :  192



**Array Indexing**

We can index elements in an array using square brackets and indices. For 1D arrays, indexing works the same as with Python list.


In [18]:
# 1D array of random integers
# get 10 integers from 0 to 22

num_samples = 10
integers = np.random.randint(23, size=num_samples)
integers

array([ 5,  8,  5,  4, 10,  0,  5, 13, 13, 19])

In [19]:
# indexing 1D array needs only one index
# get 3rd element (remember: NumPy unlike MATLAB is 0 based indexing)
integers[2]

5

In [20]:
# The reshape(3, -1) function reshapes the 1D array into a 2D array with 3 rows. The -1 means that NumPy will automatically determine the correct number of columns
#based on the total number of elements (45 in this case).
twoD_arr= np.arange(1,46).reshape(3, -1)
twoD_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]])

In [21]:
# indexing 2D array needs only two indices.
# then it returns a scalar value

# value at last row and last column
twoD_arr[-1,-1]

45

In [22]:
# howevthe  if we use only one (valid) index then it returns a 1D array

# get all elments in the last row
twoD_arr[-1]  # or twoD_arr[-1, ] or twoD_arr[-1, :]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [23]:
# remember `gaussian` is a 3D array.
gaussian

array([[[ 0.37370734,  0.77707572,  0.39479029,  2.06444282],
        [ 0.21155995, -1.92305457, -0.53447782,  0.48880559],
        [-1.14977691, -0.23090384,  0.98816237, -0.6766298 ]],

       [[-0.34154272,  1.2993996 , -0.2224029 ,  0.10834705],
        [-0.6096913 ,  0.01739315, -0.66088687, -0.5212048 ],
        [ 1.69474931,  1.64248018, -0.17405049, -1.46282699]]])

In [24]:
# So, a 2D array is returned when using one index

# return last slice
gaussian[-1]

array([[-0.34154272,  1.2993996 , -0.2224029 ,  0.10834705],
       [-0.6096913 ,  0.01739315, -0.66088687, -0.5212048 ],
       [ 1.69474931,  1.64248018, -0.17405049, -1.46282699]])

In [25]:
# a 1D array is returned when using a pair of indices

# return first row from last slice
gaussian[-1,0]

array([-0.34154272,  1.2993996 , -0.2224029 ,  0.10834705])

In [26]:
# return last row from last slice
gaussian[-1,-1]


array([ 1.69474931,  1.64248018, -0.17405049, -1.46282699])

In [27]:
# return last element of row of last slice
idx=(-1,-1,-1)
gaussian[idx]


-1.462826992896081



We can also assign new values to elements in an array using indexing:


In [28]:
# updating the array by assigning values


# updating the array by assigning values
# truncation will happen if there's a datatype mismatch
# pringt (integers)

integers[2]=99.21
integers


array([ 5,  8, 99,  4, 10,  0,  5, 13, 13, 19])

**Index slicing**

Index slicing is the technical name for the syntax M[lower:upper:step] to extract part of an array. Negative indices counts from the end of the array (positive index from the begining):


In [29]:
integers

array([ 5,  8, 99,  4, 10,  0,  5, 13, 13, 19])

In [30]:
# slice a portion of the array
# similar to Python iterator slicing
# x[start:stop:step]

# get last 5 elements
integers[-5:]

#if `stop` is ommitted then is'll be sliced till the end of the array
# by default, step is 1

array([ 0,  5, 13, 13, 19])

In [31]:


# get alternative elements (every other element) from the array
# equivalently step = 2
integers[::2]

array([ 5, 99, 10,  5, 13])

In [32]:
# reversing the array
integers[::-1]

array([19, 13, 13,  5,  0, 10,  4, 99,  8,  5])

In [33]:
# forward traveersal of array
integers[3::]

array([ 4, 10,  0,  5, 13, 13, 19])

In [34]:
# reverse travesal of array (starting from 4th element)
integers[3::-1]

array([ 4, 99,  8,  5])

Array slices are mutable: if they are assigned a new value the original array from which the slice was extracted is modified:

In [35]:
integers

array([ 5,  8, 99,  4, 10,  0,  5, 13, 13, 19])

In [36]:
# assign new values to the last two elements
integers[-2:]=[-2,-46]
integers

array([  5,   8,  99,   4,  10,   0,   5,  13,  -2, -46])

**nD arrays**

In [37]:
# a 2D array
twenty = (np.arange(4*5)).reshape(4,5)
twenty

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
# slice first 2 rows and 3 columns
twenty[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [39]:
# slice and get only the corner elements
# three "jumps" along dimension 0
# four "jumps" along dimension 1
twenty[::3, ::4]

array([[ 0,  4],
       [15, 19]])

In [40]:
# reversing the order of elements along columns (i.e. along dimension 0)
twenty[::-1, ...]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [41]:
# reversing the order of elements along rows (i.e. along dimension 1)
twenty[..., ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [42]:


# reversing the rows and columns (i.e. along both dimensions)
twenty[::-1, ::-1]



array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [43]:
# or more intuitively
np.flip(twenty, axis=(0,1))


# or equivalently
np.flipud(np.fliplr(twenty))
np.fliplr(np.flipud(twenty))

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])


**Fancy indexing**

Fancy indexing is the name for when an array or a list is used in-place of an index:


In [44]:
# a 2D array
twenty

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
# get 2nd, 3rd, and 4th rows
row_indices = [1, 2, 3]
twenty[row_indices]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
#In this part, col_indices specifies the columns to be extracted: the 2nd column, the 3rd column, and the last column (using -1 for the last element).
col_indices = [1, 2, -1] # 3rd column and last column
twenty[row_indices, col_indices]

array([ 6, 12, 19])

In [47]:
# mask has to be of the same shape as the array to be indexed; else IndexError would be thrown
# mask for indexing alternate elements in the array
row_mask = np.array([True, False, True, False, True, False, True, False, True, False])

integers[row_mask]


array([ 5, 99, 10,  5, -2])

In [48]:
integers

array([  5,   8,  99,   4,  10,   0,   5,  13,  -2, -46])

In [49]:
# alternatively
row_mask = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype= np.bool_)
integers[row_mask]

array([ 5, 99, 10,  5, -2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [50]:


range_arr = np.arange(0, 10, 0.5)
range_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [51]:
mask = (range_arr > 5) * (range_arr < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [52]:
range_arr[mask]

array([5.5, 6. , 6.5, 7. ])

In [53]:
# or equivalently

mask = (5 < range_arr) & (range_arr < 7.5)
range_arr[mask]


array([5.5, 6. , 6.5, 7. ])


Linear operations

Vectorizing the code is key to writing efficient numerical calculation with Python/NumPy. This means that, as much as possible, a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.
Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.


In [54]:
vec = np.arange(0, 5)

vec

array([0, 1, 2, 3, 4])

In [55]:
# note that original `vec` still remains unaffected since we haven't assigned the new array to it.
vec * 2

array([0, 2, 4, 6, 8])

In [56]:
vec + 2

array([2, 3, 4, 5, 6])


Element-wise array-array operations

When we add, subtract, multiply, and divide arrays with each other, the default behaviour is element-wise operations:



In [57]:
arr = np.arange(4 * 5).reshape(4, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
np.matmul(arr, (arr.T))

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

In [59]:
print(vec.shape, arr.shape)

# shape has to match
vec * arr

(5,) (4, 5)


array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76]])

In [60]:
# else no broadcasting will happen and an error is thrown
print(vec[:, None].shape)

vec[:, None] * arr

(5, 1)


ValueError: operands could not be broadcast together with shapes (5,1) (4,5) 

In [ ]:
# however, this would work
vec[:4, None] * arr

**Matrix operations**

What about the glorified matrix mutiplication? There are two ways. We can either use the dot function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments. Or you can use the @ operator in Python 3

In [61]:
# matrix-matrix product
print(arr.T.shape, arr.shape)
np.dot(arr.T, arr)

(5, 4) (4, 5)


array([[350, 380, 410, 440, 470],
       [380, 414, 448, 482, 516],
       [410, 448, 486, 524, 562],
       [440, 482, 524, 566, 608],
       [470, 516, 562, 608, 654]])

In [62]:
# matrix-vector product
print("shapes: ", arr.shape, vec.shape)
np.dot(arr, vec) #but not thsi: np.dot(vec,arr)

shapes:  (4, 5) (5,)


array([ 30,  80, 130, 180])

In [63]:
# matrix-vector product
print("shapes: ", arr.shape, vec.shape)
np.dot(arr, vec) #but not this: np.dot(vec, arrr)

shapes:  (4, 5) (5,)


array([ 30,  80, 130, 180])

In [64]:


col_vec = vec[:, None]
print("shapes: ", (col_vec).T.shape, (col_vec).shape)

# inner product
(col_vec.T) @ (col_vec)

shapes:  (1, 5) (5, 1)


array([[30]])


Stacking and repeating arrays

Using function repeat, tile, vstack, hstack, and concatenate we can create larger vectors and matrices from smaller ones:


In [65]:
a = np.array([[1, 2], [3, 4]])
a


array([[1, 2],
       [3, 4]])

In [66]:
# repeat each element 3 times
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [67]:
# tile the matrix 3 times
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [68]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [69]:
# concatenate a and b along axis 0
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
# concatenate a and b along axis 1
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

**hstack and vstack**

In [71]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])


**Copy and "deep copy"**

For performance reasons, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference).


In [73]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [74]:
# now array B is referring to the same array data as A
B = A
B

array([[1, 2],
       [3, 4]])

In [75]:
# changing B affects A
B[0,0] = 10

A


array([[10,  2],
       [ 3,  4]])

If we want to avoid such a behavior, so that when we get a new completely independent object B copied from A, then we need to do a so-called "deep copy" using the function copy:

In [76]:
B = np.copy(A)


**Vectorizing functions**

As mentioned several times by now, to get good performance we should always try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.


In [77]:
def Theta(x):
    """
    scalar implementation of the Heaviside step function.
    """
    if x >= 0:
        return 1
    else:
      return 0

In [78]:
v1 = np.array([-3,-2,-1,0,1,2,3])

Theta(v1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

That didn't work because we didn't write the function Theta so that it can handle a vector input...

To get a vectorized version of Theta we can use the Numpy function vectorize. In many cases it can automatically vectorize a function:


In [79]:
Theta_vec = np.vectorize(Theta)

In [80]:
Theta_vec(v1)

array([0, 0, 0, 1, 1, 1, 1])

we can also implement the function to accept a vector input from the beginning (requires more effort but might give better performance):

In [81]:
def Theta(x):
  """
  Vector-aware implementation of the Heaviside step function.
  """
  return 1 * (x >= 0)

In [82]:
Theta(v1)

array([0, 0, 0, 1, 1, 1, 1])

In [83]:
# it even works with scalar input
Theta(-1.2), Theta(2.6)

(0, 1)


# Exercices



## Exercise 1: Creating and Manipulating NumPy Arrays

    Create a 1D NumPy array from the list [5, 10, 15, 20, 25]. Convert the array to type float64 and print it.

    Create a 2D NumPy array from the nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Print the shape and size of the array.

    Create a 3D NumPy array with random values of shape (2, 3, 4). Print the number of dimensions and the shape of the array.



In [84]:
# Create a 1D NumPy array
arr_1d = np.array([5, 10, 15, 20, 25])

# Convert to float64
arr_1d = arr_1d.astype(np.float64)

# Print the array
print(arr_1d)

[ 5. 10. 15. 20. 25.]


In [85]:
# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the shape and size
print("Shape:", arr_2d.shape)

# Print the size
print("Size:", arr_2d.size)

Shape: (3, 3)
Size: 9


In [86]:
# Create a 3D NumPy array with random values
arr_3d = np.random.rand(2, 3, 4)

# Print the number of dimensions
print("Number of Dimensions:", arr_3d.ndim)

# Print the shape
print("Shape:", arr_3d.shape)

Number of Dimensions: 3
Shape: (2, 3, 4)



## Exercise 2: Advanced Array Manipulations

  * Create a 1D NumPy array with the numbers from 0 to 9. Reverse the array and print it.

  * Create a 2D NumPy array with the numbers from 0 to 11, arranged in a 3x4 shape. Extract a subarray consisting of the first two rows and the last two columns, and print it.

  * Create a 2D NumPy array of shape (5, 5) with random integers between 0 and 10. Replace all elements greater than 5 with 0 and print the modified array.



In [87]:
# Create a 1D array
arr_1d = np.arange(10)

# Reverse the array
reversed_arr = arr_1d[::-1]

# Print the reversed array
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


In [88]:
# Create a 2D array
arr_2d = np.arange(12).reshape(3, 4)

# Extract subarray
subarray = arr_2d[:2, 2:]

# Print the subarray
print(subarray)

[[2 3]
 [6 7]]


In [89]:
# Create a 2D array with random integers
arr_2d = np.random.randint(0, 10, size=(5, 5))


# Replace elements greater than 5 with 0
arr_2d[arr_2d > 5] = 0

# Print the modified array
print(arr_2d)

[[2 3 3 2 0]
 [3 4 4 3 1]
 [0 0 0 5 0]
 [4 3 2 2 0]
 [3 5 0 0 0]]



## Exercise 3: Array Initialization and Attributes

  * Create a 3x3 identity matrix using NumPy and print its attributes: ndim, shape, size, itemsize, and nbytes.

  * Create an array of 10 evenly spaced numbers between 0 and 5 using numpy.linspace(). Print the array and its datatype.

  * Create a 3D array of shape (2, 3, 4) with random values from a standard normal distribution. Print the array and the sum of all elements.



In [90]:
# Create a 3x3 identity matrix
identity_matrix = np.identity(3)

# Print attributes
print("dimensions:", identity_matrix.ndim)
print("shape:", identity_matrix.shape)
print("size:", identity_matrix.size)
print("itemsize:", identity_matrix.itemsize)
print("Total number of bytes in arr:", identity_matrix.nbytes)

dimensions: 2
shape: (3, 3)
size: 9
itemsize: 8
Total number of bytes in arr: 72


In [91]:
# Create an array of evenly spaced numbers
spaced_numbers = np.linspace(0, 5, 10)

# Print the array and its datatype
print("Array:", spaced_numbers)
print("Datatype:", spaced_numbers.dtype)

Array: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Datatype: float64


In [92]:
# Create a 3D array of shape (2, 3, 4) with random values from a standard normal distribution
random_array = np.random.randn(2, 3, 4)

# Print the array and the sum of all elements
print("Array:", random_array)
print("Sum of elements:", np.sum(random_array))

Array: [[[ 0.08164309  0.58669126  1.60130337  0.41479491]
  [-0.41427572  0.54799203  0.80058066 -0.31454971]
  [-1.11075141  0.80996672 -0.19309405 -1.41492987]]

 [[ 0.03062823  0.58011839 -1.64760231  1.18101999]
  [-0.95794882 -0.57210766 -0.66149181  0.36142353]
  [-0.13325034 -0.13014987 -0.13911588 -0.16908218]]]
Sum of elements: -0.8621874663903851



## Exercise 4: Fancy Indexing and Masking

  * Create a 1D NumPy array with random integers between 0 and 50 of size 20. Use fancy indexing to extract elements at indices [2, 5, 7, 10, 15] and print them.

  * Create a 2D NumPy array with random integers between 0 and 30 of shape (4, 5). Use a boolean mask to select all elements greater than 15 and print them.

  * Create a 1D NumPy array of 10 random integers between -10 and 10. Use a boolean mask to set all negative values to zero and print the modified array.



In [93]:
# Create a 1D array with random integers
random_array = np.random.randint(0, 50, size=20)
print("random_array",random_array)

# Extract elements using fancy indexing
extracted_elements = random_array[[2, 5, 7, 10, 15]]

# Print the extracted elements
print("Extracted elements:", extracted_elements)

random_array [30 13 18  2 45 14 14 41  7 12  2 38 37 20 37 38 13 37  7 42]
Extracted elements: [18 14 41  2 38]


In [94]:
# Create a 2D array with random integers
random_array_2d = np.random.randint(0, 30, size=(4, 5))
print("random_array_2d", random_array_2d)

# Create a boolean mask
mask = random_array_2d > 15

# Select elements using the mask
selected_elements = random_array_2d[mask]

# Print the selected elements
print("Selected elements:", selected_elements)

random_array_2d [[15 17 21 29 21]
 [ 8 10  8  8  2]
 [12 18 27 15 29]
 [ 6  0 15 23  6]]
Selected elements: [17 21 29 21 18 27 29 23]


In [95]:
# Create a 1D array of 10 random integers between -10 and 10
random_integers = np.random.randint(-10, 10, size=10)

# Create a boolean mask for negative values
negative_mask = random_integers < 0

# Set negative values to zero using the mask
random_integers[negative_mask] = 0

# Print the modified array
print("Modified array:", random_integers)

Modified array: [2 0 0 0 0 6 9 2 7 2]



## Exercise 5: Combining and Splitting Arrays

  * Create two 1D NumPy arrays of length 5 with random integers between 0 and 10. Concatenate the two arrays and print the result.

  * Create a 2D NumPy array of shape (6, 4) with random integers between 0 and 10. Split the array into two equal parts along the row axis and print them.

  * Create a 2D NumPy array of shape (3, 6) with random integers between 0 and 10. Split the array into three equal parts along the column axis and print them.



In [96]:
# Create two 1D arrays with random integers
array1 = np.random.randint(0, 10, size=5)
array2 = np.random.randint(0, 10, size=5)

# Concatenate the arrays
concatenated_array = np.concatenate((array1, array2))

# Print the result
print("Concatenated array:", concatenated_array)

Concatenated array: [7 0 1 7 0 5 2 1 6 3]


In [97]:
# Create a 2D array with random integers
array_2d = np.random.randint(0, 10, size=(6, 4))

# Split the array into two equal parts along the row axis
part1, part2 = np.split(array_2d, 2, axis=0)

# Print the result
print(part1)
print(part2)

[[4 9 2 7]
 [1 5 6 0]
 [3 6 1 2]]
[[0 8 9 3]
 [5 4 6 8]
 [8 9 8 3]]


In [98]:
# Create a 2D array with random integers
array_2d = np.random.randint(0,10, size=(3,6))

# Split the array into three equal parts along the column axis
part1, part2, part3 = np.split(array_2d,3,axis=1)

# Print the result
print (part1)
print (part2)
print (part3)

[[9 8]
 [1 6]
 [6 0]]
[[2 1]
 [1 2]
 [3 6]]
[[7 5]
 [9 6]
 [5 3]]



### Exercise 6: Mathematical Functions and Aggregations

  * Create a 1D NumPy array with random integers between 1 and 100 of size 15. Compute and print the mean, median, standard deviation, and variance of the array.

  * Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 50. Compute and print the sum of each row and each column.

  * Create a 3D NumPy array of shape (2, 3, 4) with random integers between 1 and 20. Find the maximum and minimum values along each axis and print them.




In [99]:
# Create a 1D array with random integers
array_1d = np.random.randint(1, 101, size=15)

# Calculate statistics
mean = np.mean(array_1d)
median = np.median(array_1d)
std_dev = np.std(array_1d)
variance = np.var(array_1d)

# Print the statistics
print("array_1d:", array_1d)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

array_1d: [  1 100  30  90  29  46  70  33  93  53  66  33  72  44   8]
Mean: 51.2
Median: 46.0
Standard Deviation: 29.111738754896336
Variance: 847.4933333333332


In [100]:
# Create a 2D array with random integers
array_2d = np.random.randint(1, 51, size=(4, 4))

    # Calculate sum of each row
row_sums = np.sum(array_2d, axis=1)

    # Calculate sum of each column
column_sums = np.sum(array_2d, axis=0)

    # Print the results
print("array_2d:\n", array_2d)
print("Row sums:", row_sums)
print("Column sums:", column_sums)

array_2d:
 [[36 14 42 40]
 [24 50  1 24]
 [19 18 27 17]
 [41  7 47  3]]
Row sums: [132  99  81  98]
Column sums: [120  89 117  84]


In [101]:
# Create a 3D array with random integers
array_3d = np.random.randint(1,21, size=(2, 3, 4))

# Find maximum and minimum values along each axis
max_values_axis0 = np.max(array_3d, axis=0)
min_values_axis0 = np.min(array_3d, axis=0)

max_values_axis1 = np.max(array_3d, axis=1)
min_values_axis1 = np.min(array_3d, axis=1)

max_values_axis2 = np.max(array_3d, axis=2)
min_values_axis2 = np.min(array_3d, axis=2)

    # Print the results
print("array_3d:\n", array_3d)

print("\nMaximum values along axis 0:\n", max_values_axis0)
print("Minimum values along axis 0:\n", min_values_axis0)

print("Maximum values along axis 1:\n", max_values_axis1)
print("Minimum values along axis 1:\n", min_values_axis1)

print("Maximum values along axis 2:\n", max_values_axis2)
print("Minimum values along axis 2:\n", min_values_axis2)

array_3d:
 [[[ 2 14  6 16]
  [ 9  5  9  7]
  [ 6  4 20  8]]

 [[ 8 19 10 10]
  [16 20  6  7]
  [17  3  9  5]]]

Maximum values along axis 0:
 [[ 8 19 10 16]
 [16 20  9  7]
 [17  4 20  8]]
Minimum values along axis 0:
 [[ 2 14  6 10]
 [ 9  5  6  7]
 [ 6  3  9  5]]
Maximum values along axis 1:
 [[ 9 14 20 16]
 [17 20 10 10]]
Minimum values along axis 1:
 [[2 4 6 7]
 [8 3 6 5]]
Maximum values along axis 2:
 [[16  9 20]
 [19 20 17]]
Minimum values along axis 2:
 [[2 5 4]
 [8 6 3]]



## Exercise 7: Reshaping and Transposing Arrays

  * Create a 1D NumPy array with the numbers from 1 to 12. Reshape the array to a 2D array of shape (3, 4) and print it.

  * Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Transpose the array and print the transposed array.

  * Create a 2D NumPy array of shape (2, 3) with random integers between 1 and 10. Flatten the array to 1D and print the result.



In [104]:
# Create a 1D array
arr_1d = np.arange(1, 13)

# reshape to a 2D array
arr_2d = arr_1d.reshape(3, 4)

# Print the result
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [102]:
# Create a 2D array with random integers
arr_2d = np.random.randint(1,11, size=(3, 4))
print ("\n",arr_2d)

# Transpose the array
transposed_arr = arr_2d.T

# Print the transposed array
print("\nTranspose:\n",transposed_arr)


 [[ 6 10  5  3]
 [ 2  1  8 10]
 [ 8  8  9  9]]

Transpose:
 [[ 6  2  8]
 [10  1  8]
 [ 5  8  9]
 [ 3 10  9]]


In [103]:
# Create a 2D array
arr_2d = np.random.randint(1, 11, size=(2, 3))
print ("2d array :\n",arr_2d)
#flatten the array
arr_1d = arr_2d.flatten()

#print the result
print("Flattened array:", arr_1d)

2d array :
 [[1 3 1]
 [7 1 6]]
Flattened array: [1 3 1 7 1 6]



## Exercise 8: Broadcasting and Vectorized Operations

  * Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Subtract the mean of each column from the respective column elements and print the result.

  * Create two 1D NumPy arrays of length 4 with random integers between 1 and 5. Use broadcasting to compute and print the outer product of the two arrays.

  * Create a 2D NumPy array of shape (4, 5) with random integers between 1 and 10. Add 10 to all elements of the array that are greater than 5 and print the modified array.

